### ISSUE TITLE
auth() is not doing anything

### ISSUE THREAD

**Issue by darmie** [ptgamr/cordova-google-play-game#18]
The app is not signing into google play. `googleplaygame.auth()` is not doing anything!!

**Comment by darmie** [comment]
Fixed

**Comment by darmie** [comment]
Fixed!

**Comment by gee-whiz** [comment]
good day Darmie

how did you fix this error 

thanks

**Comment by darmie** [comment]
@gee-whiz Sorry, I later ran into other issues. I now use https://github.com/artberri/cordova-plugin-play-games-services

**Comment by gee-whiz** [comment]
Thank a lot man I'll try it

**Comment by gee-whiz** [comment]
Sorry to bother you again man.I've installed the plugin but when I test it says **Uncaught ReferenceError: playGamesServices is not defined** so even on the device it won't do anything

**Comment by darmie** [comment]
Did you follow the steps correctly? Did you enter your application ID?

**Comment by gee-whiz** [comment]
yes Like this **cordova plugin add https://github.com/ptgamr/cordova-google-play-game.git --variable APP_ID="my app id here"**

**Comment by gee-whiz** [comment]
sorry like this **cordova plugin add https://github.com/artberri/cordova-plugin-play-games-services.git --variable APP_ID="app id"**

**Comment by darmie** [comment]
Did you check the error message in the Android log cat?

**Comment by gee-whiz** [comment]
good idea man let me setup a log cat

**Comment by gee-whiz** [comment]
Darmie Thanks a lot for the help I manged to make it work by upgrading my android to 5.0** cordova platform update android@5.0.0**

**Comment by darmie** [comment]
Cool.
